### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by kootenpv** [grantjenks/python-wordsegment#14]
Even though it is licensed with Apache 2, I believe it cannot be used in any commercial application as the license of the data only allows it to be used for educational/research purposes? Is that correct?

~~Maybe, in this case, it is possible to decouple the data, and allow open source unigrams/bigrams to be gathered from somewhere?~~
Noticed the "[Using a Different Corpus](http://www.grantjenks.com/docs/wordsegment/using-a-different-corpus.html)" link

**Comment by grantjenks** [comment]
I'm not sure. Where did you **see** that "it cannot be used in any commercial application as the license of the data only allows it to be used for educational/research purposes?"

**Comment by kootenpv** [comment]
I've wanted to use the trillion corpus before... so I remember it from then.
You link to: https://catalog.ldc.upenn.edu/LDC2006T13 which under license contains a link to: https://catalog.ldc.upenn.edu/license/web-1t-5-gram-version-1.pdf
Then look at section 1.1 and 1.2

**Comment by grantjenks** [comment]
Hmm, that looks conclusive. I don't think I got it from LDC though. I thought I got it from the book publisher but I can't find that data now. And likely the publisher would have inherited the same restriction.

Perhaps I should make that more clear on the landing page.

How do you want to use it?

**Comment by grantjenks** [comment]
There's also corpus data at http://storage.googleapis.com/books/ngrams/books/datasetsv2.html

**Comment by kootenpv** [comment]
That one also mentions Creative Commons, which is not fully compatible with Apache I believe (w.r.t. commercial use). It's fun for experimentation though.

**Comment by grantjenks** [comment]
When I click the link it says: "You are free to: Adapt — remix, transform, and build upon the material
for any purpose, **even commercially**.

**Comment by kootenpv** [comment]
Oh my bad! I see that this is a different version. Great! I will have a go myself :)
