### ISSUE TITLE
How to add custom values?

### ISSUE THREAD

**Issue by vebsun** [grantjenks/python-wordsegment#16]
Hello GrantJenks,
this project is very very interesting and fantastic job. I have gone through your Using a Different Corpus references and added value according to the steps defined, but word segmentation is not returning the value as expected, for example I would like to see "lineno" output as "line no". could you please guide me on this challenge.
Once again. it is a real fantastic work. to my knowledge, no other similar works are closer to your accomplishments.

**Comment by grantjenks** [comment]
Here's what worked for me:

```python
In [1]: import wordsegment as ws

In [2]: segmenter = ws.Segmenter()

In [3]: segmenter.load()

In [4]: segmenter.unigrams['lineno']
Out[4]: 1414293.0

In [5]: segmenter.bigrams['line no']
KeyError: 'line no'

In [6]: # Google: "lineno" --> 417e3 results

In [7]: # Google: "line no" --> 2.54e6 results

In [8]: segmenter.bigrams['line no'] = segmenter.unigrams['lineno'] * 2.54e6 / 417e3

In [10]: segmenter.segment('thelinenoisten')
Out[10]: ['the', 'line', 'no', 'is', 'ten']
```

Thanks for the kind words!

Please consider making a donation to the project at https://gumroad.com/l/wordsegment
