### ISSUE TITLE
unigrams

### ISSUE THREAD

**Issue by raedaf** [grantjenks/python-wordsegment#17]
hello
thank you for your great effort
i want to ask you
 what is the solution when i get an error when call
 unigrams[unknown word]
i want to return 0 not get an error  how i can fix that?

**Comment by grantjenks** [comment]
Unigrams are a Python dictionary so you can use:

    wordsegment.UNIGRAMS.get(some_word, 0)

Also, remember to call ``wordsegment.load()``!
