### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ffxz** [grantjenks/python-wordsegment#18]
when i use 'from wordsegment import clean' command, i get the information"ImportError: cannot import name clean"

**Comment by ffxz** [comment]
i know, if i want to use clean function, i should type in command as follow:
import wordsegment
c = wordsegment.Segmenter()
c.clean('i am a boy')

then, the result is : 'iamaboy'

**Comment by grantjenks** [comment]
Fixed at 887c187 and deployed at 1.2.0
